// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Hkwk3aUB2lVPIHOEMre4AlwjPk0JlOw',
    appId: '1:826203318448:web:499b541465f89254ec7375',
    messagingSenderId: '826203318448',
    projectId: 'scribble-7d161',
    authDomain: 'scribble-7d161.firebaseapp.com',
    storageBucket: 'scribble-7d161.appspot.com',
    measurementId: 'G-JSZ5DZRSVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOIwWl_6TpcXv01ivZEpe0fhpPLY9c7UQ',
    appId: '1:826203318448:android:820fb177ede26448ec7375',
    messagingSenderId: '826203318448',
    projectId: 'scribble-7d161',
    storageBucket: 'scribble-7d161.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRUJzho6nDYgZg5wxMU1R4AwnnwG_1ZOc',
    appId: '1:826203318448:ios:5a1961ff133affd3ec7375',
    messagingSenderId: '826203318448',
    projectId: 'scribble-7d161',
    storageBucket: 'scribble-7d161.appspot.com',
    iosBundleId: 'com.gdsc.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRUJzho6nDYgZg5wxMU1R4AwnnwG_1ZOc',
    appId: '1:826203318448:ios:65c3e2377b4bb6aaec7375',
    messagingSenderId: '826203318448',
    projectId: 'scribble-7d161',
    storageBucket: 'scribble-7d161.appspot.com',
    iosBundleId: 'com.gdsc.myNotes.RunnerTests',
  );
}
